# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Not a Futurist
subtitle: ou qualquer outra coisa
email: leualemax@gmail.com
disqus:
  shortname: leualemax
description: >- # this means to ignore newlines until "baseurl:"
  This is my spot in internet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: leualemax
collections:
  games:
    output: true
  systems:
    output: true
defaults:
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game"
  - scope:
      path: ""
      type: "systems"
    values:
      layout: "system"
copyrights:
  - text: icone em svg - Computer by Flatart from the Noun Project
    link: https://thenounproject.com/search/?q=pc%20gamer%20outline&i=2298505#_=_
  - text: icone em svg - new nintendo 3ds by tezar tantular from the Noun Project
    link: https://thenounproject.com/kerismaker/collection/game-consoles-outline/?i=2012304
  - text: icone em svg - nintendo switch by tezar tantular from the Noun Project
    link: https://thenounproject.com/kerismaker/collection/game-consoles-outline/?i=2012268
  - text: icone em svg - playstation 4 by tezar tantular from the Noun Project
    link: https://thenounproject.com/kerismaker/collection/game-consoles-outline/?i=2012279
  - text: icone em svg - Playstation 3 by tezar tantular from the Noun Project
    link: https://thenounproject.com/kerismaker/collection/game-consoles-outline/?i=2012278
  - text: issues by amante de icono from the Noun Project
    link: https://thenounproject.com/search/?q=issue&i=1446467
# Build setting
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
